### ISSUE TITLE
File not found error when generating cfg

### ISSUE THREAD

**Issue by Gabrielsvc** [dongqi-DQ/WRF4PALM#10]
As it currently is in the repository, when running the `run_config_wrf4palm.py` script for the first time breaks down due to the folder `cfg_files` not being present. I think this can be fixed either by verifying if the folder exists in the `generate_cfg` function(which I think is a poor solution):

> def generate_cfg(case_name, dx, dy, dz, nx, ny, nz, west, east, south, north, centlat, centlon, z_origin):
       cfg = pd.DataFrame({'dx': [dx], 'dy': [dy], 'dz': [dz], 'nx': [nx], 'ny': [ny], 'nz': [nz], 'z_origin': [z_origin],
                                        'north': [north], 'south': [south], 'east': [east], 'west': [west], 'centlat':[centlat], 'centlon':[centlon]})
    import os
    if not os.path.exists('cfg_files'):
        os.makedirs('cfg_files')
    cfg.to_csv('cfg_files/'+ case_name + '.cfg', index=None)
    print('cfg file is saved: '+case_name)

 or adding an empty folder by default in the repository.

Cheers,
Gabriel

**Comment by dongqi-DQ** [comment]
Thank you very much for reporting this, @Gabrielsvc! I've applied a fix so the folders would be created if they did not exist.

I will close this issue now.
