### ISSUE TITLE
Refactoring of quick_compare.py and run_config_wrf4palm.py

### ISSUE THREAD

**Issue by xanfus** [dongqi-DQ/WRF4PALM#15]
An enhancement. To keep _quick_compare.py_ up to date with main script with less effort, both are to be refactored.

**Comment by dongqi-DQ** [comment]
This should be fixed with this commit https://github.com/dongqi-DQ/WRF4PALM/pull/20

I will close this issue now and will keep both scripts updated in the future. 

Feel free to reopen it if the issue persists.
