### ISSUE TITLE
Calculation of vertical levels does not work with stretching

### ISSUE THREAD

**Issue by RJVogel** [dongqi-DQ/WRF4PALM#18]
Hello everyone,

I just tested this code and noticed that the function `calc_stretch` does not get all the stretching parameters and hence throws an error, when dz_stretch_factor is larger than 1. This is how the function call looks:
`calc_stretch(z, dz, zw, dz_stretch_level)`

And this is how it should look:
`calc_stretch(z, dz, zw, dz_stretch_factor, dz_stretch_level, dz_max):`

I fixed it and now it works. I could do a pull request if you want, but it was really just a minor fix.

Have a nice weekend!
Julian

**Comment by dongqi-DQ** [comment]
Thanks @RJVogel 
I've applied the fixes you mentioned. Will add this feature to my future testing list.
