### ISSUE TITLE
dynamical_util/loc_dom.py - calc_stretch: two times dz_stretch_level in definition and call of function 

### ISSUE THREAD

**Issue by KlemensBarfus** [dongqi-DQ/WRF4PALM#22]
In dynamical_util/loc_dom.py - calc_stretch the parameter dz_stretch_level appears two times in the definition of the function and in the call of the function. Best would be to skip one.

**Comment by dongqi-DQ** [comment]
This was fixed here 468cc9da60e6e337bc94c84e9fdbbc3d11490d82.

**Comment by dongqi-DQ** [comment]
I will close the issue as this should be solved. Feel free to reopen it if any related problem popped up.
