### ISSUE TITLE
Wrong geostrophic wind calculation

### ISSUE THREAD

**Issue by OliverMaasEnercon** [dongqi-DQ/WRF4PALM#25]
In version 1.1 the geostrophic wind is calculated from the horizontal gradient of the geopotential height. Since the geopotential height is zero everywhere at the surface, the gradient and thus also the geostrophic wind is zero at the surface, which is wrong.

I think the gradients should be calculated in the p-system (along pressure levels) and not in the z-system (along height levels) to obtain non-zero values for the geostrophic wind at (and near) the surface.

In version 1.0 the geostrophic wind was calculated from the pressure field. Maybe it is an option to switch back to that method?

**Comment by dongqi-DQ** [comment]
I have added an option in the namelist and the code so you can choose which one to use (see v1.1.2).

For p-system:
```
[case]
geostrophic = "p",
```
For z-system:
```
[case]
geostrophic = "z",
```

I will close this issue for now. But feel free to reopen it if further discussion is needed.

**Comment by OliverMaasEnercon** [comment]
Thank you very much for the fast reply and the fast and extensive code changes!
I now obtain realistic geostrophic wind profiles.

However, I needed to fix a small issue to get the code to work:
The allocation of `grad_x `and `grad_y` in `geostrophic.py` uses the length of `array_1d_lat` and `array_1d_lon`, which turned out to be 2 grid points larger than `array_d2_press` and thus an error is raised during calculation of `grad_x` and `grad_y`.
I used the shape of `array_2d_press` directly to allocate  `grad_x` and `grad_y` and it worked:
`    gradx = np.zeros((np.shape(array_2d_press)[0],np.shape(array_2d_press)[1]))`
`    grady = np.zeros((np.shape(array_2d_press)[0],np.shape(array_2d_press)[1]))`

Another comment on the naming:
The current stearing with `geostrophic = "p"` and `geostrophic = "z"` and the respective comments in the code and the readme  are a bit misleading. Maybe I was not clear enough on that in my first comment.
- The "p"-option uses the pressure variable (not pressure levels) and computes the gradients in the z-levels, so along x and y.
- The "z"-option should be named e.g. "gph" because it uses the geopotential height variable and computes (or should compute) the gradients in the p-levels.

 Unfortunately I have no good english reference that I can provide. Maybe you also want to fix these two small issues.
Thanks a lot again.

**Comment by dongqi-DQ** [comment]
Thanks very much for spotting the errors and mistakes I made in the documentation. I'm sorry that I did not look into the physics while editing the documentation/code.  

I've edited the code and reworded the documentation so that the option "p" now refers to the pressure variable being used and "z" refers to the geopotential height being used. Hopefully it's clear now.

**Comment by OliverMaasEnercon** [comment]
Great, thank you so much!
