### ISSUE TITLE
'DataArray' object has no attribute 'drop_duplicates' in line 145

### ISSUE THREAD

**Issue by yujeongdo** [dongqi-DQ/WRF4PALM#30]
Dear Dongqi,
An error occurs at line 145 of run_config_wrf4palm.py.
The wrfout file that I used has 10 minutes interval.
The error log is as below, and if you need any other information, please announce me.
Thank you.

$ python3.8 run_config_wrf4palm.py namelist.wrf4palm.rev
cfg_files folder created
dynamic_files folder created
Reading WRF
Traceback (most recent call last):
  File "run_config_wrf4palm.py", line 145, in <module>
    ds_wrf[variables] = ds_raw[variables].drop_duplicates("time", keep="last")
  File "/home/username/anaconda3/lib/python3.8/site-packages/xarray/core/common.py", line 239, in __getattr__
    raise AttributeError(
AttributeError: 'DataArray' object has no attribute 'drop_duplicates'

**Comment by dongqi-DQ** [comment]
Hi there, It seems like this error comes from xarray. Can you please check your xarray version and see if it is 0.19.0 or later?

**Comment by yujeongdo** [comment]
My xarray version was 0.18.0.
After update the xarray to version 2023.1.0, it works well.
Thank you for your help!

**Comment by dongqi-DQ** [comment]
Great! Will close this issue now.
