### ISSUE TITLE
error with calc_stretch in quick_compare.py

### ISSUE THREAD

**Issue by yujeongdo** [dongqi-DQ/WRF4PALM#33]
Hi,
I got an error with quick_compare.py.

python quick_compare.py namelist.wrf4palm pr PT

Traceback (most recent call last):
  File "quick_compare.py", line 92, in <module>
    z, zw = calc_stretch(z, dz, zw, dz_stretch_level)
TypeError: calc_stretch() missing 2 required positional arguments: 'dz_stretch_level' and 'dz_max'
(base) [yjdo2@stormy00 WRF4PALM-WRF4PALM_v1.1.2]$ python3.8 quick_compare.py namelist.wrf4palm pr PT
Traceback (most recent call last):
  File "quick_compare.py", line 92, in <module>
    z, zw = calc_stretch(z, dz, zw, dz_stretch_level)
TypeError: calc_stretch() missing 2 required positional arguments: 'dz_stretch_level' and 'dz_max'

So I added arguments like this:
z, zw = calc_stretch(z, dz, zw, dz_stretch_factor, dz_stretch_level, dz_max)

But it still doesn't work. How can I fix it?

Thank you for your time.

**Comment by dongqi-DQ** [comment]
I'm aware that there might be some inconsistency in the vertical stretching function in the quick compare script. Can you provide your namelist so I can run a quick test on this?

**Comment by dongqi-DQ** [comment]
I have updated the `quick_compare.py` script (3258efe14a98a881f8c4aa02d5526421c61426f4) and it was working with my own namelist and WRF files.

If the error is not solved, please provide the new error message and your namelist to help me locate the issue.

**Comment by yujeongdo** [comment]
Sorry for late answer.
I have tested with updated script, but it still don't work.

The error message:
$ python3.8 quick_compare.py namelist.wrf4palm pr PT
Reading WRF
cfg file is saved: 20230731
Please enter the timestamp (yyyy-mm-dd-hh): 2023-07-30-12
qt.qpa.xcb: X server does not support XInput 2
qt.qpa.xcb: XKeyboard extension not present on the X server
qt.qpa.xcb: QXcbConnection: XCB error: 1 (BadRequest), sequence: 164, resource id: 88, major code: 130 (Unknown), minor code: 47
The X11 connection broke: I/O error (code 1)
XIO:  fatal IO error 2 (No such file or directory) on X server "localhost:14.0"
      after 250 requests (248 known processed) with 0 events remaining.

Now I think the problem is on my server.

**Comment by dongqi-DQ** [comment]
I think this is something related to X11 forwarding from your server to your screen. The quick compare script will pop up the figure directly instead of saving it locally. You may try to edit the script to save the figure in your server and view it later, e.g. send it back to your local machine where a png viewer is available.

**Comment by dongqi-DQ** [comment]
I will close this issue now since it's an X11 issue. Feel free to reopen it if need be.
