### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by Indira-Mishra** [dongqi-DQ/WRF4PALM#35]
Hello Dongqi, 

I have been continuously getting an error in the running of the WRF4PALM run script :- 

File "run_config_wrf4palm.py", line 139, in <module>
    with salem.open_mf_wrf_dataset(wrf_files) as ds_raw:
  File "/dss/dsshome1/0C/go98roh2/py4palm/lib/python3.8/site-packages/salem/sio.py", line 1180, in open_mf_wrf_dataset
    datasets = [open_wrf_dataset(p, chunks=chunks or {}, lock=lock)
  File "/dss/dsshome1/0C/go98roh2/py4palm/lib/python3.8/site-packages/salem/sio.py", line 1180, in <listcomp>
    datasets = [open_wrf_dataset(p, chunks=chunks or {}, lock=lock)
  File "/dss/dsshome1/0C/go98roh2/py4palm/lib/python3.8/site-packages/salem/sio.py", line 972, in open_wrf_dataset
    nc = netCDF4.Dataset(file)
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'.-'

I do not understand which file does it point to that it is not able to find.
Could you help me with this?

Best Regards, 
Indira

**Comment by dongqi-DQ** [comment]
It looks like salem cannot find the wrf output file. Can you check that you have your wrf output files saved in `wrf_output` diretory and have used the correct filenames in your namelist? 

Please provide your namelist so I can further diagnose the issue. Otherwise, I wouldn't be able to help much with limited information.

**Comment by Indira-Mishra** [comment]
Hello Dongqi, 

Sorry for my late reply. We were facing some issues with our Linux machine, due to which I was unable to use it, but we have solved it now and are good to go. Thank you so much for your prompt reply to my last email. 

Yes, my output file is in the wrf_output directory. There is only one output file that I am currently trying to run.  My namelist file contains the following information:- 


[case]

case_name = "wrf4palm_chch",
max_pool = 4,
geostrophic = "p", ## calculate geostrophic wind using the variable pressure (option "p") or geopotential height  (option "z")

[domain]
palm_proj = "",                                   # projection of PALM
centlat   = -43.59000799999999,                   # latitude of domain centre
centlon   = 172.713367,                           # longitude of domain centre
nx        = 108,                                  # number of grid points along x-axis
ny        = 108,                                  # number of grid points along y-axis
nz        = 50,                                   # number of grid points along z-axis
dx        = 729.0,                                # number of grid points along x-axis
dy        = 729.0,                                # number of grid points along y-axis
dz        = 163.0,                                # number of grid points along z-axis
z_origin  = 0.0,                                  # elevated mean grid position (elevated terrain)

[stretch]
dz_stretch_factor = 1.0,        # stretch factor for a vertically stretched grid
                                # set this to 1.0 if no streching required
dz_stretch_level = 1200.0,      # Height level above which the grid is to be stretched vertically (in m)

dz_max = 30.0,                  # allowed maximum vertical grid spacing (in m)


[wrf]
wrf_path = "./dss/dsshome1/0C/go98roh2/WRF4PALM/my_directory/wrf_output"
wrf_output = "wrfout_d03_2023-04-15_00_00_00" 

interp_mode = "linear",

start_year = 2001,
start_month = 8,
start_day = 29,
start_hour = 1,

end_year = 2001,
end_month = 8,
end_day = 29,
end_hour = 3,

dynamic_ts = 3600.0,         # PALM dynamic driver update frequency

[soil]
(hash) layers for soil temperature and moisture calculation
(hash) this shall be changed depending on different cases

dz_soil = 0.01, 0.02, 0.04, 0.06, 0.14, 0.26, 0.54, 1.86,
msoil = 0.3, # dummy value in case soil moisture from WRF output is 0.0

Warm regards, 
Indira

**Comment by dongqi-DQ** [comment]
The WRF directory you specified seems to be wrong.  
I assume you have the WRF4PALM script in `/dss/dsshome1/0C/go98roh2/WRF4PALM/`  
The `wrf_path` you provided has a dot before the directory, which will point to the wrong directory. Because the dot points to the current directory, then what WRF4PALM sees is `/dss/dsshome1/0C/go98roh2/WRF4PALM/dss/dsshome1/0C/go98roh2/WRF4PALM/my_directory/wrf_output/`  

You may want to try `/dss/dsshome1/0C/go98roh2/WRF4PALM/my_directory/wrf_output/` (without the dot at the beginning and with a / at the end).

Or in case you have the WRF4PALM script in `/dss/dsshome1/0C/go98roh2/WRF4PALM/`, try `./my_directory/wrf_output/`

**Comment by Indira-Mishra** [comment]
Thank you so much! I did as you said and also added additional commas at the end of both the commands `wrf_path` and `wrf_output` . It helped me get out or this error at least. It is funny that how so small looking corrections can take up so much of your time.
