### ISSUE TITLE
Error with nearest.py

### ISSUE THREAD

**Issue by Indira-Mishra** [dongqi-DQ/WRF4PALM#36]
**Hello Dongqi,

So, I was facing this error:-** 

(wrf4palm) go98roh2@cm2login1:~/WRF4PALM/my_directory> python run_config_wrf4palm.py namelist.wrf4palm
Reading WRF
cfg file is saved: wrf4palm_chch
Traceback (most recent call last):
  File "/dss/dsshome1/0C/go98roh2/WRF4PALM/my_directory/run_config_wrf4palm.py", line 248, in <module>
    west_idx,east_idx,south_idx,north_idx = framing_2d_cartesian(lons_wrf,lats_wrf, west,east,south,north,dx_wrf, dy_wrf)
  File "/dss/dsshome1/0C/go98roh2/WRF4PALM/my_directory/dynamic_util/nearest.py", line 28, in framing_2d_cartesian
    if lons_wrf[nearest_nidx, nearest_eidx]-east<dx_wrf:
IndexError: index 195 is out of bounds for axis 1 with size 195

**To correct it, I made some changes to my nearest.py file :-** 

def framing_2d_cartesian(lons_wrf,lats_wrf, west,east,south,north, dx_wrf, dy_wrf):
    ## lower left corner
    ll_distance = np.abs(lats_wrf-south) + np.abs(lons_wrf-west)
    nearest_sidx, nearest_widx = np.unravel_index(ll_distance.argmin(),ll_distance.shape)
    if lons_wrf[nearest_sidx, nearest_widx]>west:
        nearest_widx-=1
    if lats_wrf[nearest_sidx, nearest_widx]>south:
        nearest_sidx-=1
        
    ## upper right corner
    ur_distance = np.abs(lats_wrf-north) + np.abs(lons_wrf-east)
    nearest_nidx, nearest_eidx = np.unravel_index(ur_distance.argmin(),ur_distance.shape)
    if lons_wrf[nearest_nidx, nearest_eidx]<east:
        nearest_eidx+=1

    # Ensure that nearest_eidx does not exceed the maximum index
    if nearest_eidx >= lons_wrf.shape[1]:
        nearest_eidx = lons_wrf.shape[1] - 1

    **# To make sure the east boundary of PALM domain is within the cropped WRF domain
    if lons_wrf[nearest_nidx, nearest_eidx] - east < dx_wrf:
        nearest_eidx += 1
    if nearest_eidx >= lons_wrf.shape[1]:
        nearest_eidx = lons_wrf.shape[1] - 1

    if lats_wrf[nearest_nidx, nearest_eidx] < north:
        nearest_nidx += 1
    if nearest_nidx >= lats_wrf.shape[0]:
        nearest_nidx = lats_wrf.shape[0] - 1

    # Ensure that nearest_nidx does not exceed the maximum index
    if nearest_nidx >= lats_wrf.shape[0]:
        nearest_nidx = lats_wrf.shape[0] - 1

    # to make sure the north boundary of PALM domain is within the cropped WRF domain
    if lats_wrf[nearest_nidx, nearest_eidx]-north<dy_wrf:
        nearest_nidx+=1
    return nearest_widx, nearest_eidx, nearest_sidx, nearest_nidx**

def nearest_2d(array, number):
    
    '''
    
    find nearest index value and index in a 2D array.
    
    nearest(array, number)
    
    return(nearest_number, nearest_index)
    
    '''
      
    index = np.where(np.abs(array-number) == np.nanmin(np.abs(array-number)))#index is single pair of naturals, if only array isn't anywhere cartesian.
    idx, idy = index[0], index[1]
    nearest_number = array[idx, idy]#1D array of length 1 or Nx of Ny.
    nearest_index = [idx[0], idy[0]]
    
    return(nearest_number[0], nearest_index)

def nearest_1d(array, number):
    
    '''
    
    find nearest index value and index in array.
    
    nearest(array, number)
    
    return(nearest_number, nearest_index)
    
    '''
    
    nearest_index = np.where(np.abs(array-number) == np.nanmin(np.abs(array-number)))
    nearest_index = int(nearest_index[0][0])
    nearest_number = array[nearest_index]
    
    return(nearest_number, nearest_index)
   

**And then I started encountering :-** 

Reading WRF
cfg file is saved: wrf4palm_chch
194 194 194 194
PALM domain size is smaller than one WRF grid cell size.
Please consider re-configure your PALM domain.
Stopping...

Could you suggest why...

**Comment by dongqi-DQ** [comment]
First of all, for any further issues and this one, can you please provide your namelist? And I'm wondering what is your WRF grid spacing?

From the error message you got (and WRF4PALM aborted itself), I think your PALM domain is too small, e.g. you have a 3km WRF but your PALM domain is 2km wide. 

And from the namelist you provided in issue #35, it seems like you are running WRF4PALM for Christchurch? The lat/lon are exactly the same as what we have in the sample namelist. Can you please check that the latitude and longitude of your PALM domain centre is correct?

**Comment by Indira-Mishra** [comment]
[case]

case_name = "wrf4palm_chch",
max_pool = 4,
geostrophic = "p", ## calculate geostrophic wind using the variable pressure (option "p") or geopotential height  (option "z")

[domain]
palm_proj = "",                                   # projection of PALM
centlat   = 48.15102,                             # latitude of domain centre
centlon   = 11.569,                               # longitude of domain centre
nx        = 600,                                  # number of grid points along x-axis
ny        = 600,                                  # number of grid points along y-axis
nz        = 200,                                   # number of grid points along z-axis
dx        = 80.0,                                # number of grid points along x-axis
dy        = 80.0,                                # number of grid points along y-axis
dz        = 10.0,                                # number of grid points along z-axis
z_origin  = 0.0,                                  # elevated mean grid position (elevated terrain)

[stretch]
dz_stretch_factor = 1.0,        # stretch factor for a vertically stretched grid
                                # set this to 1.0 if no streching required
dz_stretch_level = 1200.0,      # Height level above which the grid is to be stretched vertically (in m)

dz_max = 30.0,                  # allowed maximum vertical grid spacing (in m)


[wrf]
wrf_path = "/dss/dsshome1/0C/go98roh2/WRF4PALM/my_directory/wrf_output/",
wrf_output = "wrfout_d03_2023-04-15_00_00_00", 

interp_mode = "linear",

start_year = 2023,
start_month = 4,
start_day = 15,
start_hour = 8,

end_year = 2023,
end_month = 4,
end_day = 15,
end_hour = 15,

dynamic_ts = 10800.0,         # PALM dynamic driver update frequency

[soil]
layers for soil temperature and moisture calculation
this shall be changed depending on different cases

dz_soil = 0.01, 0.02, 0.04, 0.06, 0.14, 0.26, 0.54, 1.86,
msoil = 0.3, # dummy value in case soil moisture from WRF output is 0.0


That is my namelist. As you suggested, I changed the coordinates (sorry, I am new to the field of modelling) and I also corrected the domain size. I could now successfully run it with my wrf output.
